version: '3.2'
services:
  docker-challenge:
    image: docker-challenge-image
    container_name: docker-challenge-container
    build: .
    ports:
      - 8081:8080
      - 8085:8085
    volumes:
      - ./src/main/resources/config:/docker-challenge/config