apiVersion: v1
kind: Pod
metadata:
  name: docker-challenge
  namespace: tosan
  labels:
    app: docker-challenge
    version: v1
spec:
  containers:
    - name: docker-challenge
      image: localhost:5000/docker-challenge
      ports:
        - name: web
          containerPort: 8080
          protocol: TCP
  terminationGracePeriodSeconds: 30