apiVersion: v1
kind: Service
metadata:
  name: docker-challenge-srv
  namespace: tosan
spec:
  selector:
    app: docker-challenge
    version: v1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: non-secure
      targetPort: web
      nodePort: 30445